spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/znfx?serverTimezone=GMT%2b8
#    url: jdbc:mysql://114.115.151.17:6000/znfx?serverTimezone=GMT%2b8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
data:
  mongodb:
#    url: mongodb://114.115.151.17:6001/  # 远程服务器
    url: mongodb://localhost:27017/
    database:
      trajectory: znfx_trajectory
      process: znfx_process_data
      centreTra: znfx_centre_trajectory
      match: znfx_match
      default: znfx

logging:
  level:
    root: info
    cn.njust.label: debug

logstash:
  host: localhost
server:
  port: 8080

